---
databaseSg:
  Type: AWS::EC2::SecurityGroup
  DependsOn:
  - vpc
  - appServerSg
  Properties:
    GroupDescription: Security for the DB
    VpcId:
      Ref: vpc
    SecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId:
        Fn::GetAtt:
        - appServerSg
        - GroupId
    - IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId:
        Fn::GetAtt:
        - appServerSg
        - GroupId
databaseSubnetGroup:
  Type: AWS::RDS::DBSubnetGroup
  DependsOn:
    - subnetA
    - subnetB
    - subnetC
  Properties:
    DBSubnetGroupDescription: .
    SubnetIds:
    - Ref: subnetA
    - Ref: subnetB
    - Ref: subnetC
database:
  Type: AWS::RDS::DBInstance
  DependsOn:
    - vpc
    - databaseSubnetGroup
  DeletionPolicy: Retain
  Properties:
    VPCSecurityGroups:
    - Ref: databaseSg
    DBSubnetGroupName:
      Ref: databaseSubnetGroup
    DBInstanceClass: db.t2.small
    MasterUsername: thedude
    MasterUserPassword: thepass1
    PubliclyAccessible: false
    AllocatedStorage: 10
    StorageType: gp2
    Engine: Postgres
databaseDNS:
  Type: AWS::Route53::RecordSetGroup
  Properties:
    HostedZoneName: tedder.me.
    Comment: Database Server DNS
    RecordSets:
    - Name:
        Fn::Join:
        - '_'
        - - Ref: StackId
          - db.tedder.me.
      Type: CNAME
      SetIdentifier: DB SRV
      TTL: 300
      Weight: 1
      ResourceRecords:
      - Fn::GetAtt:
        - database
        - Endpoint.Address
